delete http://localhost:3003/api/blogs/60631892367347b4d7a0c26e
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbGFtZWwiLCJpZCI6IjYwNjJmMjZmYWMxZjJhYWJlMDAyYzU3OSIsImlhdCI6MTYxNzEwNjg1MH0.hEuoOXbn_mCvo96BxSd0I8-jnCQvSv_ajjQMSdmSx2o